# Change these first
owner: rosalindfranklinuniv # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Rosalind Franklin University Network 
    url: https://selfservice.rosalindfranklin.edu/Student/Account/Login
  - name: ADP
    url: https://workforcenow.adp.com/
  - name: Athena Health
    url: https://identity.athenahealth.com/
  - name: Boxer Library
    url: https://www.rosalindfranklin.edu/Library/
  - name: CastleBranch
    url: https://discover.castlebranch.com/    
  #- name: Cobblestone
  #  url: https://rosalindfranklin.cobblestone.software/
  - name: COI Smart
    url: https://rosalindfranklin.coi-smart.com/
  - name: D2L Brightspace
    url: https://d2l.rosalindfranklin.edu/d2l/home
  - name: Engage
    url: https://rosalindfranklin.campuslabs.com/engage
  #- name: Examsoft
  #  url: https://ei.examsoft.com/GKWeb/login/rosalindfranklin
  - name: Exxat PRISM
    url: https://auth.rosalindfranklin.edu/auth/realms/rfu/protocol/saml/clients/ExxatPRISM 
  - name: Exxat V.3
    url: https://apps.exxat.com/Fusion/Account/Login?ReturnUrl=%2f 
  - name: Test System
    url: https://apps.estestsystemdownxxat.com/Fusion/Account/Login?ReturnUrl=%2f     
  #- name: Google Employee Email
  #  url: https://mail.google.com/ 
  #- name: Google Student Email
  #  url: https://mail.google.com/ 
  - name: Helixcard WebPay
    url: https://webpay.rosalindfranklin.edu/webdeposit/
  - name: IM Leagues
    url: https://www.imleagues.com/SSOSignUp.aspx
  #- name: InSite
  #  url: https://insite.rosalindfranklin.edu/Pages/Default-New.aspx 
  - name: Interfolio
    url: https://home.interfolio.com/14700
  - name: ITS Help Desk
    url: https://support.rosalindfranklin.edu/?format=portal 
  - name: KnowBe4
    url: https://training.knowbe4.com/ 
  - name: Maxient
    url: https://cm.maxient.com/
  - name: Med+Proctor
    url: https://secure.medproctor.com/
  - name: One45
    url: https://rfums-cms.one45.com/
  - name: Panopto
    url: https://rosalindfranklin.hosted.panopto.com/ 
  - name: Poll Everywhere
    url: https://id.polleverywhere.com/ 
  #- name: Qualtrics
  #  url: https://rosalindfranklin.qualtrics.com/homepage/ui 
  - name: Risk Management
    url: https://www.lossfreerx.com/
  - name: SAP Concur
    url: https://us2.concursolutions.com/home
  - name: Self-Service
    url: https://selfservice.rosalindfranklin.edu/Student/Account/Login
  #- name: Slate
  #  url: https://apply.rosalindfranklin.edu/manage/
  - name: Tutoring Appointments
    url: https://rfu.mywconline.com/register
  #- name: WebPrint (LRC)
  #  url: https://webprint.rosalindfranklin.edu:2443/login
  - name: Workday 
    url: https://login.adaptiveinsights.com/
  - name: Zoom
    url: https://rosalindfranklin.zoom.us/     
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.rosalindfranklin.edu
  #baseUrl: /up
  logoUrl: https://raw.githubusercontent.com/w6cC5cP74g9c/up/master/RFUMS_seal_rgb.png
  favicon: https://raw.githubusercontent.com/w6cC5cP74g9c/up/master/RFUMS_seal_rgb.png
  #theme: dark
  #themeurl: https://uptime.rosalindfranklin.edu/my-custom-theme.css 
  links:
    - rel: stylesheet
      href: https://uptime.rosalindfranklin.edu/my-custom-theme.css
  name: RFUMS System Statuses
  introTitle: "Welcome to the Rosalind Franklin University of Medicine and Science System Status Page"
  introMessage: This dashboard displays status information for all critical services at Rosalind Franklin University of Medicine and Science. On weekends, ITS regularly performs system and network maintenance. The dashboard will be updated whenever status information for any service changes. Please check back at any time to obtain current status information.
  navbar:
    #- title: Status
    #  href: /
    - title: Helixnet
      href: https://helixnet.rosalindfranklin.edu
    - title: Helpdesk
      href: https://support.rosalindfranklin.edu/?format=portal     
    - title: Insite
      href: https://insite.rosalindfranklin.edu      
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO    
i18n:  
  footer: To report an incident, contact the [Rosalind Franklin University HelpDesk](https://support.rosalindfranklin.edu/?format=portal)    
status-page:
    theme: "light"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
